### ISSUE TITLE
Bug: duplicate repositories can be added to dashboard

### ISSUE THREAD

**Issue by git-srinivas** [open-sauced/open-sauced#1219] opened 2021-10-09 19:15 UTC
### Describe the bug

When a user  login to the app, there are see two sections on the dashboard. One is the repo recommendations list and the other  is dashboard repo list.
 
Expected behaviour:
When user try to add a recommended repo item for one time or multiple times, it should be added to the dashboard repo list only once.

Actual behaviour:
When the user  add a recommended repo item for multiple times, it gets added to the dashboard list for multipl times. Which is causing duplicate records of the same repo item in the dashboard list. Which is redundant and not expected. 

Proposed solution:
We can keep a block loader or spinner on the recommended repo list, till the repo item disappers( or till the sync action completes)?

I am attaching a screenshot (from my mobile browser) below, which depicts the same
![Screenshot_20211010-003135_Chrome](https://user-images.githubusercontent.com/11858762/136671296-482dca0b-5c0a-4ae3-ac14-130783e1b99c.jpg)

### Steps to reproduce

1.Login to the app
2. Go to repository recommendation list
3. Click on add button  continuously for 2 or more  times
4. Reload the app and you can see duplicate repositories on the dashboard repo list

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile, Tablet

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-vortex** [comment] 2021-10-10 02:22
Cannot reproduce, could you provide additional instructions

**Comment by git-srinivas** [comment] 2021-10-10 04:32
1. Go to repository recommendations
2. Click on + symbol  for 3 times. Dont wait for 30 seconds or sync to complete
3. just click on add button continuously
4. Reload the app and you can see the duplicate repo records
[Here](https://github.com/git-srinivas/open-sauced-goals/blob/main/data.json) is my data json that contains the same

**Comment by 0-vortex** [comment] 2021-10-10 09:02
Managed to reproduce but only on desktop.

> Duplicate repositories can be added to dashboard. As a user, if I added a repo as favorite. A single list item would be sufficient to track updates.

Understand this is a real issue now but In the future, could you kindly check with @open-sauced/triage before filing bugs with missing information? It helps us reduce the back and forth for a fix that could be a few lines of code!

**Comment by git-srinivas** [comment] 2021-10-10 10:06
> Managed to reproduce but only on desktop.
> 
> > Duplicate repositories can be added to dashboard. As a user, if I added a repo as favorite. A single list item would be sufficient to track updates.
> 
> Understand this is a real issue now but In the future, could you kindly check with @open-sauced/triage before filing bugs with missing information? It helps us reduce the back and forth for a fix that could be a few lines of code!

Since our app is a web application, the bug can be replicated in both desktop and mobile. I added the screen shot from my mobile browser only. 

@0-vortex  If you feel the bug is redundant, I can close this and update the triage bug?

**Comment by git-srinivas** [comment] 2021-10-10 11:24
@0-vortex  I agree. This is the first bug i ever raised  with open source projects/apps. Thanks for the guidance. I updated the bug description and steps to reproduce. Please check and let me know if it is fine :)

**Comment by mtfoley** [comment] 2021-10-13 03:38
I got a chance to re-reproduce this tonight after #1220 landed - the situation is a little better since repo does get added in goals list when using + button in recommendations list. However, the recommendations list doesn’t repopulate with the newly added goal filtered out.  Seems like `stars` variable may need to be refactored to implement `useState()` 
https://github.com/open-sauced/open-sauced/blob/42472e2ad5072c4fd8e849a6a2f5c6c3369dc3f6/src/components/RepositoryGoals.js#L51-L54

**Comment by 0-vortex** [comment] 2021-10-21 06:42
A visual and sorting fix is dropping in #1247 - that doesn't solve the issue of adding repositories in the UI or to the `open-sauced-goals` repository however it should simplify the local state changes required to make adding duplicates impossible from the UI.

Hope this helps!

**Comment by 0-vortex** [comment] 2022-01-01 17:23
@git-srinivas are you still keen to work on this?

**Comment by RozzaysRed** [comment] 2022-10-13 23:12
.take

**Closed** 2022-10-24 22:55 UTC
Labels: 🐛 bug
