### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by sujitagarwal** [open-sauced/open-sauced#712] opened 2020-06-18 14:21 UTC
### Describe the bug
While logging in, Permission is being asked for Public and Private repositories.

### To Reproduce
1. try to login for the first time / access revoked account 
2. check the permissions window

### Expected behavior
Private Repository access should not be asked for.

### Screenshots 

![image](https://user-images.githubusercontent.com/1915009/85031858-c9fc6f80-b19c-11ea-8502-961cfb5e03e4.png)

**Comment by yg** [comment] 2020-06-18 14:25
Dupe of #689

**Comment by sujitagarwal** [comment] 2020-06-18 14:27
Oops, my bad. I should have looked into the history of bugs...

**Closed** 2020-06-18 14:26 UTC
Labels: duplicate
