### ISSUE TITLE
Duplicate repository listing

### ISSUE THREAD

**Issue by Brawrdon** [open-sauced/open-sauced#555] opened 2020-05-26 21:50 UTC
### Describe the bug

A small issue but when trying to add the same repository more than once it creates a unique listing.

### To Reproduce

1.  Go to dashboard
2. Add a repo
3. Add the same repo again... and again... and again...

### Expected behavior

The repo shouldn't be listed again. Potentially a message could appear to let them know the repo already exists which provides an anchor link to the repo in the list. This might be useful for a user who has a lot of repos / pagination is a thing.

### Screenshots

![image](https://user-images.githubusercontent.com/9751243/82953304-6c607300-9fa2-11ea-96ca-df85c00b0f29.png)

**Comment by bdougie** [comment] 2020-05-26 23:07
This a great issues will hopefully be solved with #384

**Comment by bdougie** [comment] 2020-06-16 13:18
I don't this will be addressed in #384. Instead, I think we can create FindOrCreate type mutation. TBH I have never thought to do this until now. 

Here is how I would approach this. 

1. Create a new **fetchGoalByName** query in https://github.com/open-sauced/open-sauced/blob/master/src/lib/apiGraphQL.js
2. In the [createGoal](https://github.com/open-sauced/open-sauced/blob/master/src/lib/apiGraphQL.js#L427) function. Add a line to fetchGoalByName. If an issue is found with the provide name, return that goal and reopen the issue if it is closed (be sure to search open and close issues, also just return the last issue if it there are multiple). If the issue is not found by name, proceed with createGoal.

An example is [sails.js](https://sailsjs.com/documentation/reference/waterline-orm/models/find-or-create)
An example in [sequelize](https://sequelize.org/v3/docs/models-usage/)

**Comment by yg** [comment] 2020-07-07 11:33
Fixed in #728

**Closed by yg** 2020-07-07 11:33 UTC
Labels: accepting prs, 🐛 bug, 💄 completed
