### ISSUE TITLE
Bug: When pressing the opensauced logo to go to the homepage I get sent to an old version

### ISSUE THREAD

**Issue by wotta** [open-sauced/open-sauced#1436] opened 2022-05-10 12:46 UTC
### Describe the bug

1. Go to: https://docs.opensauced.pizza/
2. Click on the logo
3. You get redirected to: https://opensauced.pizza/
4. This the homepage version: Open Sauced v0.42.5

![Screenshot 2022-05-10 at 14 45 51](https://user-images.githubusercontent.com/13332240/167631551-33080e7b-13a8-44dc-93f2-e1cfb95b1e6a.png)

This should be the latest version of the homepage as shown below.

![Screenshot 2022-05-10 at 14 45 34](https://user-images.githubusercontent.com/13332240/167631495-6ef5720c-cfda-42c8-b59a-731a66facf26.png)
e

### Steps to reproduce

1. Go to: https://docs.opensauced.pizza/
2. Click on the logo
3. You get redirected to: https://opensauced.pizza/
4. This the homepage version: Open Sauced v0.42.5

### Affected services

opensauced.pizza, docs.opensauced.pizza

### Platforms

Desktop

### Browsers

Other (add additional context)

### Environment

Production

### Additional context

Brave browser V1.38.111

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment] 2022-05-10 12:52
Hey, thanks for adding this issue, back in `v0.42.5` the service worker wasn't correctly checking for new versions, hence why some assets on that redirect are not loading. Refreshing the page once without cache or deleting local `*.opensauced.pizza` should fix the error locally. Unfortunately, we cannot retroactively solve `v0.42.5` but the problem is solved, currently. Do you think a page in the docs obout this issue and how to clear the session would make sense? 

cc @bdougie had this issue on stream once as well, what do you think?

**Comment by wotta** [comment] 2022-05-11 13:20
Thanks for the quick reply @0-vortex.
I'm not fully sure if the page in the docs is a needed. I have the feeling that I'm one of the handful of people who will encounter this issue.

But since this repository is based on getting people introduced with opensource contributions, I am not gonna shoot down an opportunity for someone in the very basics of opensource contributions.

**Comment by bdougie** [comment] 2022-05-11 15:18
Yeah, we need to clear the cache aggressively for users. The site was getting 2300 uniques a month before the change, so I imagine a not insignificant amount of people will encounter this.

**Comment by bdougie** [comment] 2022-05-11 21:30
The solution for anyone who encounters this is to unregister the service worker. We can work on a fix to automate this, but for now, I think this is a viable solution for the 165 (out of 2300 uniques referenced above) active users.

![image](https://user-images.githubusercontent.com/5713670/167950780-05c2a7c9-9661-4f5d-9db6-38089562b2e9.png)

**Comment by bdougie** [comment] 2022-05-17 22:42
I have added the following code to a Netlify snippet injection. It's deployed, just need someone to confirm it works now.

```js
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })
```

**Comment by 0-vortex** [comment] 2022-05-17 22:46
> I have added the following code to a Netlify snippet injection. It's deployed, just need someone to confirm it works now.
> 
> ```js
> navigator.serviceWorker.getRegistrations().then(function(registrations) {
>  for(let registration of registrations) {
>   registration.unregister()
> } })
> ```

This makes the service worker stop working for everyone - with no registered resources you would never have the app available offline, the issue is visible by the lack of `SW is ready to handle offline requests.` message in the console :D

**Comment by bdougie** [comment] 2022-05-17 22:48
My reason for putting it in netlify was to fix it now and remove it a month or so. I would rather have the sw not work than get pings that the site is not working entirely a user. 

Path of least resistance?

**Comment by wotta** [comment] 2022-05-18 09:21
Unfortunately I am not able to test this behaviour because I already removed my service worker.
Is there a way to visit an old version of the deployment to activate the old SW?

**Comment by 0-vortex** [comment] 2022-10-24 22:51
Closing this as won't fix - we might merge app and hot and when that happens, this could be corrected, however might not happen this year! 🍕

**Closed by 0-vortex** 2022-10-24 22:51 UTC
Labels: 🐛 bug, 👀 needs triage
