### ISSUE TITLE
Bug: Empty Dashboard page after login. Null Error in console.

### ISSUE THREAD

**Issue by sujitagarwal** [open-sauced/open-sauced#713] opened 2020-06-18 14:26 UTC
### To Reproduce
1. Login to opensauced.pizza
2. After successful login, a blank page is being rendered after a short flickering of the menu bar.
3. Inspect the debug window.

### Expected behavior
Dashboard should show up after logging in.

### Screenshots
![image](https://user-images.githubusercontent.com/1915009/85032367-60309580-b19d-11ea-8cd4-aac9682c90b0.png)

### Desktop

- OS: Win10
- Browser: Chrome
- Version: 83

**Logs attached**

[opensauced.pizza-1592490335630.log](https://github.com/open-sauced/open-sauced/files/4799170/opensauced.pizza-1592490335630.log)

**Comment by yg** [comment] 2020-06-18 14:27
@sujitagarwal Can you give some title for the issues you reporting!

**Comment by sujitagarwal** [comment] 2020-06-18 14:28
Added. @yg

**Comment by yg** [comment] 2020-06-18 14:29
Dupe of #617

**Closed by yg** 2020-06-18 14:29 UTC
Labels: duplicate
